[tool.poetry]
name = "seamless-communication"
version = "0.1.0"
description = "Foundational Models for State-of-the-Art Speech and Text Translation"
authors = ["Seamless Communication <costajussa@meta.com>"]
license = "CC-BY-NC 4.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pre-commit = "^3.5.0"
datasets = "^2.14.5"
torchaudio = "^2.1.0"
soundfile = "^0.12.1"
librosa = "^0.10.1"
fairseq2 = "^0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
black = "^23.9.1"
flake8 = "^6.1.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
